[tool.poetry]
name = "udp-socket"
version = "0.1.0"
description = ""
authors = ["Barmanjii"]
readme = "README.md"
packages = [{include = "udp_socket"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
